from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from pydantic import BaseModel, Field
from backend.core.database import get_db
from backend.models.user import User
from backend.models.device_token import DeviceToken
from backend.services.auth_service import get_current_user

router = APIRouter()

class RegisterTokenRequest(BaseModel):
    expo_push_token: str = Field(..., description="Expo push token generated by the client")
    platform: str = Field(..., pattern="^(ios|android)$", description="Target mobile platform")

@router.post("/register-token", status_code=201)
async def register_token(
    request: RegisterTokenRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    try:
        result = await db.execute(
            select(DeviceToken).where(DeviceToken.expo_push_token == request.expo_push_token)
        )
        token_record = result.scalar_one_or_none()
        
        if token_record:
            token_record.user_id = current_user.id
            token_record.platform = request.platform
        else:
            token_record = DeviceToken(
                user_id=current_user.id,
                expo_push_token=request.expo_push_token,
                platform=request.platform
            )
            db.add(token_record)
            
        await db.commit()
        return {"status": "success", "message": "Device token registered"}
    except Exception as e:
        await db.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to register token: {str(e)}")
